### ISSUE TITLE
no such table: accounts_profile

### ISSUE THREAD

**Issue by TusharKapoor23** [wingkwong/django-expense-tracker#3]
After running

`python manage.py migrate`
`python manage.py runserver`

and trying to register at /register throws an error 

`Request Method: | POST`
`Request URL: http://127.0.0.1:8000/register/`
`Django Version: 2.0.4`
`Exception Type: OperationalError`
`Exception Value: no such table: accounts_profile`

**Comment by TusharKapoor23** [comment]
Upon further investigation I needed to run 

`python manage.py migrate --run-syncdb`

to create the table account_profile, consider adding this to the Installation part!

**Comment by wingkwong** [comment]
Thanks for the comment. 

syncdb has been deprecated in 1.9. For those who are using > 1.9, try to run makemigrations and migrate. Clearly, I've missed it in README.md. I'll update it ASAP.
